---
dependencies: []

galaxy_info:
  author: Heather Huggins
  description: Configuring new Logstash slave nodes
  company: NA
  license: BSD
  min_ansible_version: 1.4
  platforms:
  - name: Debian
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  categories:
    - system
