### roles/hardened/tasks/main.yml
###
### Hardens Ubuntu servers
###
### Authored 3/2015 by Heather Huggins
---

# Patching and updating the system (CIS Section 1)
- include: patch.yml

# Securing the filesystem (CIS Section 2)
# Include this again later.

# Secure boot settings (CIS Section 3)
- include: boot.yml

# Additional process hardening (CIS Section 4)
- include: additionalprocess.yml

# OS Services (CIS Sections 5 & 6)
- include: services.yml
