### roles/hardened/tasks/main.yml
###
### Hardens Ubuntu servers
###
### Authored 3/2015 by Heather Huggins
---

# Patching and updating the system (CIS Section 1)
- include: patch.yml

# Securing the filesystem (CIS Section 2)
- include: filesystem.yml
