### roles/hardened/tasks/networkconfig.yml - Secures network configuration
### Authored 2015 by Heather Huggins
###
### Covers the following CIS Benchmark sections:
### 7.1.1 Disable IP Forwarding
### 7.1.2 Disable Send Packet Redirects
### 7.2.1 Disable Source Routed Packet Acceptance
### 7.2.2 Disable ICMP Redirect Acceptance
### 7.2.3 Disable Secure ICMP Redirect Acceptance
### 7.2.4 Log Suspicious Packets
### 7.2.5 Enable Ignore Broadcast Requests
### 7.2.6 Enable Bad Error Message Protection
### 7.2.7 Enable RFC-recommended Source Route Validation
### 7.3.1 Disable IPv6 Router Advertisements
### 7.3.2 Disable IPv6 Redirect Acceptance
### 7.3.3 Disable IPv6

---

- name: Disable unneeded network parameters
  sysctl: >
   name={{ item }}
   value=0
   state=present
   ignoreerrors=true
  with_items:
    - net.ipv4.ip_forward
    - net.ipv4.conf.all.send_redirects
    - net.ipv4.conf.default.send_redirects
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv4.conf.all.secure_redirects
    - net.ipv4.conf.default.secure_redirects
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra
    - net.ipv6.conf.all.accept_redirects
    - net.ipv6.conf.default.accept_redirects

- name: Enable secure network parameters
  sysctl: >
   name={{ item }}
   value=1
   state=present
   ignoreerrors=true
  with_items:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians
    - net.ipv4.icmp_echo_ignore_broadcasts
    - net.ipv4.icmp_ignore_bogus_error_responses
    - net.ipv4.conf.all.rp_filter
    - net.ipv4.conf.default.rp_filter
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6
    - net.ipv6.conf.lo.disable_ipv6

- name: Install TCP wrappers
  apt: pkg=tcpd state=latest update_cache=true

- name: Apply sysctl changes
  shell: sysctl -p
