### roles/snort/tasks/install.yml
###
### Runs through the installation tasks for Snort.
###
### Authored 3/2015 by Heather Huggins
---

- name: Install Barnyard2 and its dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - mysql-server
    - libmysqlclient-dev
    - mysql-client
    - autoconf
    - libtool

- name: Update mysql root password
  mysql_user: name=root password={{ mysql_root_db_pass }}

- name: Make sure Snort output is in binary format
  lineinfile: "dest=/etc/snort/snort.conf regexp='^output unified2: filename' line='output unified2: filename snort.u2, limit 128'"
