### roles/jenkins/tasks/install.yml
###
### Runs through the installation tasks for Jenkins.
###
### Authored 3/2015 by Heather Huggins
---

# Make sure install dependencies are installed
# (Department of Redundancy Department)
- name: Update apt-get
  command: apt-get update

- name: Install dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - curl
    - wget
    - docker.io
    - python-dev
    - python-pip

- name: Install boto
  pip: name=boto


# Install Jenkins
- name: Add the Jenkins repo key
  apt_key:
    url: "{{ jenkins_repo_key }}"
    validate_certs: no
    state: present

- name: Add the Jenkins repo
  apt_repository:
    repo: "{{ jenkins_repo_url }}"
    state: present
    update_cache: yes

- name: Install Jenkins
  apt: pkg=jenkins state=installed
