### roles/jenkins/tasks/plugins.yml
###
### Installs and configures Jenkins plugins. To add or remove plugins from
### the list, modify roles/jenkins/defaults/main.yml.
###
### Authored 3/2015 by Heather Huggins

---
- name: Create the updates folder
  file:
    path: /var/lib/jenkins/updates
    owner: jenkins
    group: jenkins
    mode: 0755
    state: directory

- name: Update Jenkins plugin data
  shell: >
    curl -L https://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /var/lib/jenkins/updates/default.json
    creates=/var/lib/jenkins/updates/default.json

- name: Set permissions for default.json
  file:
    path: /var/lib/jenkins/updates/default.json
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Install plugins
  shell: >
    java -jar {{ jenkins_jar }} -s http://{{ jenkins_hostname }}:8080/ install-plugin {{ item }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: "jenkins_plugins"
  notify: restart jenkins
