### roles/jenkins/tasks/users.yml
###
### Creates user configs if not already present and manages a cron job
### that regularly pushes user configs back to S3.
###
### Authored 3/2015 by Heather Huggins

---
- name: Include AWS credential variables
  include_vars: aws.yml

- name: Grab the user configs if they don't already exist
  s3:
    bucket: ops-jenkins
    object: /users/users.tar.gz
    dest: /var/lib/jenkins/users.tar.gz
    mode: get
    overwrite: false
    aws_access_key: "{{ access_key }}"
    aws_secret_key: "{{ secret_key }}"

- name: Place user configs where they should be
  shell: >
    gunzip /var/lib/jenkins/users.tar.gz && tar -xvf /var/lib/jenkins/users.tar -C /var/lib/jenkins/ && chown -R jenkins:jenkins /var/lib/jenkins/users/ && rm users.tar
  ignore_errors: yes

- name: Create cron job that compresses and uploads user data daily
  cron:
    name: "push user configs"
    minute: "0"
    hour: "3"
    weekday: "6"
    job: "tar -cvzf users.tar.gz /var/lib/jenkins/users/ && aws s3 cp --region us-east-1 /var/lib/jenkins/users.tar.gz s3://ops-jenkins/users/users.tar.gz"
